name: "Setup Canary NDK"

on:
  workflow_call:
    outputs:
      ndk-path:
        description: "Output path of the ndk"
      cache-hit:
        description: "Whether a cache hit occurred for the ndk"

jobs:
  setup-ndk:
    runs-on: ubuntu-latest
    outputs:
      ndk-path: ${{ steps.path.outputs.path }}
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
      
    steps:
      - name: NDK cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${HOME}/android-ndk-r27-canary/
          key: ${{ runner.os }}-ndk-r27-canary

      - name: Download canary ndk
        if: ${{ !steps.cache.outputs.cache-hit }}
        env:
          CANARY_URL: https://github.com/QuestPackageManager/ndk-canary-archive/releases/download/27.0.1/android-ndk-10883340-linux-x86_64.zip
        run: wget ${CANARY_URL} -O ${HOME}/ndk.zip
        shell: bash

      - name: Unzip ndk
        if: ${{ !steps.cache.outputs.cache-hit }}
        run: unzip "${HOME}/ndk.zip" -d "${HOME}/"
        shell: bash

      - name: Set output
        id: path
        shell: bash
        run: echo "path=${HOME}/android-ndk-r27-canary" >> ${GITHUB_OUTPUT}
